-- Tables
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  -- Optional fields for correctness and explanation
  correctAnswer text check (correctAnswer in ('A','B','C','D')),
  solution text,
  imageUrl text,
  imageAlt text,
  created_at timestamptz not null default now()
);

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  selected_option text not null check (selected_option in ('A','B','C','D')),
  created_at timestamptz not null default now()
);

-- RLS
alter table public.questions enable row level security;
alter table public.responses enable row level security;

-- Allow anyone to read questions
create policy if not exists "read-questions" on public.questions
for select using (true);

-- Allow anyone to insert a response with valid option
create policy if not exists "insert-responses" on public.responses
for insert with check (selected_option in ('A','B','C','D'));

-- Random question RPC (respects RLS)
create or replace function public.get_random_question()
returns setof public.questions
language sql
as $$
  select * from public.questions
  order by random()
  limit 1;
$$;

grant execute on function public.get_random_question() to anon, authenticated;


